services:
  - docker

branches:
  only:
  - master

env:
  - IMAGE_NAME=base-notebook

script:
  - docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock jupyter/repo2docker:0.10.0-127.gd9335cf jupyter-repo2docker --user-id 1000 --user-name junxiang --image-name kevinprotoss/jupiter-workspace-template --no-run https://github.com/kevinprotoss/jupiter-workspace-template

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: docker push "kevinprotoss/jupiter-workspace-template"
  on:
    branch: master

notifications:
  on_success: change
  on_failure: always
  on_start: never